


  
   
   export   const leftLists = [
     "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
    "Web-UI Design",
    "Web-Application",
    "Web-sites",
  ];
  export const rightLists = [
    "Video Production",
    "Video-Editing",
    "Advertisement",
    "Video Production",
    "Video-Editing",
    "Advertisement",
    "Video Production",
    "Video-Editing",
    "Advertisement",
    "Video Production",
    "Video-Editing",
    "Advertisement",
    "Video Production",
    "Video-Editing",
    "Advertisement",
    "Video Production",
    "Video-Editing",
    "Advertisement",
    "Video-Editing",
    "Advertisement",
    "Video Production",
    "Video-Editing",
    "Advertisement",
    "Video Production",
    "Video-Editing",
    "Advertisement",
    "Video Production",
    "Video-Editing",
    "Advertisement",
    "Video Production",
    "Video-Editing",
    "Advertisement",
    "Video Production",
    "Video-Editing",
    "Advertisement",
    "Video-Editing",
    "Advertisement",
    "Video Production",
    "Video-Editing",
    "Advertisement",
    "Video Production",
    "Video-Editing",
    "Advertisement",
    "Video Production",
    "Video-Editing",
    "Advertisement",
    "Video Production",
    "Video-Editing",
    "Advertisement",
    "Video Production",
    "Video-Editing",
    "Advertisement", "Video Production",
    "Video-Editing",
    "Advertisement",
    "Video Production",
    "Video-Editing",
    "Advertisement",
    "Video Production",
    "Video-Editing",
    "Advertisement",
    "Video Production",
    "Video-Editing",
    "Advertisement",
    "Video Production",
    "Video-Editing",
    "Advertisement",
    "Video Production",
    "Video-Editing",
    "Advertisement",
    "Video-Editing",
    "Advertisement",
    "Video Production",
    "Video-Editing",
    "Advertisement",
    "Video Production",
    "Video-Editing",
    "Advertisement",
    "Video Production",
    "Video-Editing",
    "Advertisement",
    "Video Production",
    "Video-Editing",
    "Advertisement",
    "Video Production",
    "Video-Editing",
    "Advertisement",
    "Video-Editing",
    "Advertisement",
    "Video Production",
    "Video-Editing",
    "Advertisement",
    "Video Production",
    "Video-Editing",
    "Advertisement",
    "Video Production",
    "Video-Editing",
    "Advertisement",
    "Video Production",
    "Video-Editing",
    "Advertisement",
    "Video Production",
    "Video-Editing",
    "Advertisement", "Video Production",
    "Video-Editing",
    "Advertisement",
    "Video Production",
    "Video-Editing",
    "Advertisement",
    "Video Production",
    "Video-Editing",
    "Advertisement",
    "Video Production",
    "Video-Editing",
    "Advertisement",
    "Video Production",
    "Video-Editing",
    "Advertisement",
    "Video Production",
    "Video-Editing",
    "Advertisement",
    "Video-Editing",
    "Advertisement",
    "Video Production",
    "Video-Editing",
    "Advertisement",
    "Video Production",
    "Video-Editing",
    "Advertisement",
    "Video Production",
    "Video-Editing",
    "Advertisement",
    "Video Production",
    "Video-Editing",
    "Advertisement",
    "Video Production",
    "Video-Editing",
    "Advertisement",
    "Video-Editing",
    "Advertisement",
    "Video Production",
    "Video-Editing",
    "Advertisement",
    "Video Production",
    "Video-Editing",
    "Advertisement",
    "Video Production",
    "Video-Editing",
    "Advertisement",
    "Video Production",
    "Video-Editing",
    "Advertisement",
    "Video Production",
    "Video-Editing",
    "Advertisement", "Video Production",
    "Video-Editing",
    "Advertisement",
    "Video Production",
    "Video-Editing",
    "Advertisement",
    "Video Production",
    "Video-Editing",
    "Advertisement",
    "Video Production",
    "Video-Editing",
    "Advertisement",
    "Video Production",
    "Video-Editing",
    "Advertisement",
    "Video Production",
    "Video-Editing",
    "Advertisement",
    "Video-Editing",
    "Advertisement",
    "Video Production",
    "Video-Editing",
    "Advertisement",
    "Video Production",
    "Video-Editing",
    "Advertisement",
    "Video Production",
    "Video-Editing",
    "Advertisement",
    "Video Production",
    "Video-Editing",
    "Advertisement",
    "Video Production",
    "Video-Editing",
    "Advertisement",
    "Video-Editing",
    "Advertisement",
    "Video Production",
    "Video-Editing",
    "Advertisement",
    "Video Production",
    "Video-Editing",
    "Advertisement",
    "Video Production",
    "Video-Editing",
    "Advertisement",
    "Video Production",
    "Video-Editing",
    "Advertisement",
    "Video Production",
    "Video-Editing",
    "Advertisement",
  ];
